name: LastWarGameLogic
version: '${version}'
main: org.example.gamelogic.lastwargamelogic.LastWarGameLogic
api-version: '1.20'
depend: [ProtocolLib]
commands:
  spawnflag:
    usage: /spawnflag <x> <y> <z>
    description: Spawns a flag at the given coordinates
  resetcores:
    description: Reset all cores for testing
    usage: /resetcores
    permission: op